### ISSUE TITLE
Can you share Pre-trained Model

### ISSUE THREAD

**Issue by nr-patel** [Parit99/Computer-Vision-Weight-Prediction#1]
Hi,

Can you share following three files to test this code:
label='drive/My Drive/dataset/AI/darknet/coco.names'
weight='drive/My Drive/dataset/AI/darknet/yolov3.weights'
config='drive/My Drive/dataset/AI/darknet/yolov3.cfg'

Thank you!

**Comment by Parit99** [comment]
This three files are available on the darknet website you just have to do a yolo setup, if you want to know more you can visit this website
[https://pjreddie.com/darknet/yolo/](url)
